var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
define("interfaces/hero", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});
define("interfaces/villain", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});
// Generated by https://quicktype.io
define("interfaces/pokemon", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});
define("interfaces/index", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});
define("generics/get-pockemon", ["require", "exports", "axios"], function (require, exports, axios_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.getPokemon = void 0;
    axios_1 = __importDefault(axios_1);
    const getPokemon = async (pokemonId = 1) => {
        const { data } = await axios_1.default.get(`https://pokeapi.co/api/v2/pokemon/${pokemonId}`);
        return data;
    };
    exports.getPokemon = getPokemon;
});
define("index", ["require", "exports", "generics/get-pockemon"], function (require, exports, get_pockemon_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    (0, get_pockemon_1.getPokemon)(10)
        .then(pokemon => console.log(pokemon.sprites))
        .catch(error => console.log(error))
        .finally(() => console.log('Fin de getPokemon'));
});
define("generics/generics", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.genericFunctionArrow = exports.genericFuntion = exports.printObject = void 0;
    const printObject = (argument) => {
        console.log(argument);
    };
    exports.printObject = printObject;
    function genericFuntion(argument) {
        return argument;
        // console.log(argument);
    }
    exports.genericFuntion = genericFuntion;
    const genericFunctionArrow = (argument) => {
        return argument;
    };
    exports.genericFunctionArrow = genericFunctionArrow;
});
// // import * as HeroClasses  from "./classes/Hero";
// import { Hero as SuperHero } from "./classes/Hero";
// import powers  from "./data/powers";
define("backs/genericos", ["require", "exports", "generics/generics"], function (require, exports, generics_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const deadpool = {
        name: 'Deadpool',
        realName: 'Wade Wiston Wilson',
        dangerLevel: 130
    };
    console.log((0, generics_1.genericFunctionArrow)(deadpool).realName);
});
define("data/powers", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const powers = [
        {
            id: 1,
            desc: 'Dinero'
        },
        {
            id: 2,
            desc: 'Drugs'
        },
        {
            id: 3,
            desc: 'Dinero'
        },
    ];
    exports.default = powers;
});
define("classes/Hero", ["require", "exports", "data/powers"], function (require, exports, powers_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Hero = void 0;
    powers_1 = __importDefault(powers_1);
    class Hero {
        constructor(name, powerId, age) {
            this.name = name;
            this.powerId = powerId;
            this.age = age;
        }
        get power() {
            var _a;
            return ((_a = powers_1.default.find(power => power.id === this.powerId)) === null || _a === void 0 ? void 0 : _a.desc) || 'not found';
        }
    }
    exports.Hero = Hero;
});
//# sourceMappingURL=main.js.map